### PR TITLE
fix: Support parameter that contains semicolon(":")

### PR DESCRIPTION
**Pull request by wenmin92**

### CODE REVIEW

**Comment by mattkingshott** [comment]
May I ask why you've added `hour12: false` to the `getErrorMessage` method?

**Comment by wenmin92** [comment]
> May I ask why you've added `hour12: false` to the `getErrorMessage` method?

Hi @mattkingshott , when I ran the test locally, one of the test cases failed and I found out that it was caused by inconsistent date formats.
image

**Comment by mattkingshott** [comment]
I see. I'm not sure if that would be a breaking change given that people might be performing assertions based on the output of the error message. It should probably be a major version bump.

**Comment by mattkingshott** [comment]
Released in version 5.0

**Pull request merged**
